apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ephimeral-cronjob.serviceAccountName" . }}-role-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [aca.com]
    resources: [ephimeralcronjobs]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods]
    verbs: [create]