apiVersion: batch/v1
kind: Job
metadata:
  name: "{name}"
  labels:
    job_name: "{name}"
spec:
  template:
    metadata:
      labels:
        app: "{name}"
      name: "{name}"
    spec:
      containers:
        - image: "{image}"
          name: "{name}"
          command: {command}
      restartPolicy: Never