name: Release Helm chart

on:
  push:
    branches: ["main"]
env:
  REGISTRY: ghcr.io/acll19
  CHART_NAME: ${{ github.repository }}

jobs:
  package-and-push-chart:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm 3
        uses: azure/setup-helm@v3
        with:
          version: "v3.13.1"

      - name: Package and push chart
        env:
          LOCAL_CHART_NAME: ephimeral-cronjob
        run: |
          helm package ./charts/${{ env.LOCAL_CHART_NAME }}
          export CHART_VERSION=$(grep 'version:' ./charts/${{ env.LOCAL_CHART_NAME }}/Chart.yaml | tail -n1 | awk '{ print $2 }')
          helm push ${{ env.LOCAL_CHART_NAME }}-${CHART_VERSION}.tgz oci://${{ env.REGISTRY }}
