name: Release Helm chart

on:
  push:
    branches: ["main"]
env:
  REGISTRY: ghcr.io/acll19
  CHART_NAME: ${{ github.repository }}

jobs:
  package-and-push-chart:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Install Helm 3
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.1'

      - name: Package and push chart
        run: |
            export CHART_VERSION=$(grep 'version:' ./charts/ephimeral-cronjob/Chart.yaml | tail -n1 | awk '{ print $2 }')
            helm push ${{ env.CHART_NAME }}-${CHART_VERSION}.tgz oci://${{ env.REGISTRY }}
        
